"""Compatibility facade for provider build-host helpers."""

from __future__ import annotations

from kdive.providers.build_host_config import (
    DEFAULT_BUILD_COMPONENT_ROOT,
    build_component_roots_from_env,
    load_profile_config_requirements,
    missing_config_groups,
    ref_error,
    resolve_config_bytes,
    resolve_local_ref,
    validate_config_ref,
)
from kdive.providers.build_host_execution import (
    MAKE_TIMEOUT_S,
    OBJCOPY_TIMEOUT_S,
    ReadBuildId,
    ReadBytes,
    ReadConfig,
    RunModulesInstall,
    RunStep,
    build_failure,
    launch_failure,
    read_bytes_file,
    read_text_file,
    real_read_build_id,
    real_read_config,
    real_read_kernel_image,
    real_read_vmlinux,
    real_run_make,
    real_run_modules_install,
    real_run_olddefconfig,
    run_make_target,
    workspace_failure,
)
from kdive.providers.build_host_workspace import (
    GIT_APPLY_TIMEOUT_S,
    RSYNC_TIMEOUT_S,
    STDERR_TAIL,
    Checkout,
    apply_patch,
    make_checkout,
    merge_config,
    real_checkout,
    redacted_tail,
    sync_tree,
)

__all__ = [
    "Checkout",
    "DEFAULT_BUILD_COMPONENT_ROOT",
    "GIT_APPLY_TIMEOUT_S",
    "MAKE_TIMEOUT_S",
    "OBJCOPY_TIMEOUT_S",
    "RSYNC_TIMEOUT_S",
    "ReadBuildId",
    "ReadBytes",
    "ReadConfig",
    "RunModulesInstall",
    "RunStep",
    "STDERR_TAIL",
    "apply_patch",
    "build_component_roots_from_env",
    "build_failure",
    "launch_failure",
    "load_profile_config_requirements",
    "make_checkout",
    "merge_config",
    "missing_config_groups",
    "read_bytes_file",
    "read_text_file",
    "real_checkout",
    "real_read_build_id",
    "real_read_config",
    "real_read_kernel_image",
    "real_read_vmlinux",
    "real_run_make",
    "real_run_modules_install",
    "real_run_olddefconfig",
    "redacted_tail",
    "ref_error",
    "resolve_config_bytes",
    "resolve_local_ref",
    "run_make_target",
    "sync_tree",
    "validate_config_ref",
    "workspace_failure",
]
