"""Generate docs/guide/reference/config.md from the config registry (ADR-0087).

Pure core (`render`) over the Setting list; the CLI writes the file. Mirrors
scripts/gen_tool_reference.py. Run via `just config-docs` / `just config-docs-check`.
"""

from __future__ import annotations

import sys
from collections.abc import Sequence
from pathlib import Path

from kdive.config import all_settings
from kdive.config.external_env import EXTERNAL_ENV_VARS, ExternalEnvVar
from kdive.config.registry import Setting, never_required

_EXTERNAL_SCOPE_TITLES: tuple[tuple[str, str], ...] = (
    ("test", "Test (gated suites)"),
    ("script", "Operator scripts"),
    ("guest", "In-guest helpers"),
)

_HEADER = (
    "<!-- generated by scripts/gen_config_reference.py; do not edit. "
    "Regenerate: just config-docs -->"
)
_OUT = Path(__file__).resolve().parents[1] / "docs" / "guide" / "reference" / "config.md"


def _required_label(setting: Setting) -> str:
    if setting.required_when is never_required:
        return "no"
    return "yes" if setting.required_when({}) else "conditional"


def _value_label(setting: Setting) -> str:
    if setting.secret:
        return "secret (ref only)"
    return setting.help or "—"


def render(settings: Sequence[Setting]) -> str:
    """Render the settings to grouped Markdown (pure; deterministic)."""
    by_group: dict[str, list[Setting]] = {}
    for s in settings:
        by_group.setdefault(s.group, []).append(s)
    lines = [_HEADER, "", "# Configuration reference (`KDIVE_*`)", ""]
    for group in sorted(by_group):
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| Variable | Processes | Default | Required | Value |")
        lines.append("|----------|-----------|---------|----------|-------|")
        for s in sorted(by_group[group], key=lambda x: x.name):
            procs = ", ".join(sorted(s.processes)) or "—"
            default = "—" if s.default is None else f"`{s.default}`"
            lines.append(
                f"| `{s.name}` | {procs} | {default} | {_required_label(s)} | {_value_label(s)} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_external(variables: Sequence[ExternalEnvVar]) -> str:
    """Render the non-registry ``KDIVE_*`` variables to grouped Markdown (pure; deterministic)."""
    by_scope: dict[str, list[ExternalEnvVar]] = {}
    for v in variables:
        by_scope.setdefault(v.scope, []).append(v)
    lines = [
        "# Test, tooling, and guest-helper variables",
        "",
        "Non-registry `KDIVE_*` variables read outside the process config registry — by the gated "
        "test suites, the operator setup/live-stack shell scripts, and the in-guest "
        "capture/install helpers. Catalogued in `src/kdive/config/external_env.py`.",
        "",
    ]
    for scope, title in _EXTERNAL_SCOPE_TITLES:
        scoped = by_scope.get(scope)
        if not scoped:
            continue
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Variable | Default | Description |")
        lines.append("|----------|---------|-------------|")
        for v in sorted(scoped, key=lambda x: x.name):
            default = "—" if v.default is None else f"`{v.default}`"
            lines.append(f"| `{v.name}` | {default} | {v.help} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_reference(out: Path = _OUT) -> None:
    document = render(all_settings()) + "\n" + render_external(EXTERNAL_ENV_VARS)
    out.write_text(document, encoding="utf-8")


if __name__ == "__main__":
    write_reference()
    print(f"wrote {_OUT}", file=sys.stderr)
