"""Generate the per-namespace tool reference from the live FastMCP registry (ADR-0047).

Run via `just docs` (write) / `just docs-check` (verify). The core is a pure
function over the registry's tool objects; it fails loudly on incomplete
metadata rather than emitting blanks.
"""

from __future__ import annotations

import asyncio
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from fastmcp.server.auth.providers.jwt import JWTVerifier, RSAKeyPair
from psycopg_pool import AsyncConnectionPool

from kdive.mcp.app import build_app
from kdive.security.secrets.secret_registry import SecretRegistry

_HEADER = "<!-- generated by scripts/gen_tool_reference.py; do not edit. Regenerate: just docs -->"
_REF_DIR = Path(__file__).resolve().parents[1] / "docs" / "guide" / "reference"


@dataclass(frozen=True)
class ParamDoc:
    name: str
    type: str
    required: bool
    description: str


@dataclass(frozen=True)
class ToolDoc:
    name: str
    namespace: str
    description: str
    maturity: str
    read_only: bool
    destructive: bool
    params: tuple[ParamDoc, ...] = ()


def _params(schema: dict[str, Any]) -> tuple[ParamDoc, ...]:
    props = (schema or {}).get("properties", {})
    required = set((schema or {}).get("required", []))
    out: list[ParamDoc] = []
    for name, spec in props.items():
        out.append(
            ParamDoc(
                name=name,
                type=str(spec.get("type", "any")),
                required=name in required,
                description=(spec.get("description") or "").strip(),
            )
        )
    return tuple(out)


def tool_docs(tools: list[Any]) -> list[ToolDoc]:
    """Pure registry → ToolDoc list; raises ValueError on incomplete metadata."""
    docs: list[ToolDoc] = []
    for t in tools:
        if not (t.description or "").strip():
            raise ValueError(f"{t.name}: tool has no description")
        maturity = (t.meta or {}).get("maturity")
        if maturity not in {"implemented", "partial", "planned"}:
            raise ValueError(f"{t.name}: missing/invalid maturity {maturity!r}")
        params = _params(t.parameters)
        for p in params:
            if not p.description:
                raise ValueError(f"{t.name}:{p.name}: parameter has no description")
            if "|" in p.description or "\n" in p.description:
                raise ValueError(
                    f"{t.name}:{p.name}: description has a table-breaking character (| or newline)"
                )
        ann = t.annotations
        docs.append(
            ToolDoc(
                name=t.name,
                namespace=t.name.split(".", 1)[0],
                description=t.description.strip(),
                maturity=maturity,
                read_only=bool(ann and ann.readOnlyHint),
                destructive=bool(ann and ann.destructiveHint),
                params=params,
            )
        )
    return docs


def _badges(d: ToolDoc) -> str:
    flags = [d.maturity]
    if d.read_only:
        flags.append("read-only")
    if d.destructive:
        flags.append("destructive")
    return " · ".join(f"`{f}`" for f in flags)


def render_namespace(namespace: str, docs: list[ToolDoc]) -> str:
    lines = [_HEADER, "", f"# `{namespace}` tools", ""]
    for d in sorted(docs, key=lambda x: x.name):
        lines += [f"## `{d.name}`", "", _badges(d), "", d.description, ""]
        if d.params:
            lines += ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
            for p in sorted(d.params, key=lambda x: x.name):
                req = "yes" if p.required else "no"
                lines.append(f"| `{p.name}` | `{p.type}` | {req} | {p.description} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_index(docs: list[ToolDoc]) -> str:
    lines = [_HEADER, "", "# Tool reference", "", "| Tool | Maturity |", "|---|---|"]
    for d in sorted(docs, key=lambda x: x.name):
        lines.append(
            f"| [`{d.name}`]({d.namespace}.md#{d.name.replace('.', '')}) | `{d.maturity}` |"
        )
    return "\n".join(lines) + "\n"


def _registry_tools() -> list[Any]:
    pool = AsyncConnectionPool("postgresql://unused", open=False)
    kp = RSAKeyPair.generate()
    verifier = JWTVerifier(public_key=kp.public_key, issuer="https://gen.local", audience="kdive")
    app = build_app(pool, verifier=verifier, secret_registry=SecretRegistry())
    # The erased `list` cast is intentional: the generator only reads duck-typed
    # attributes (name/description/meta/annotations/parameters), so it needs none
    # of the concrete FunctionTool type the guard test casts to for `.fn`.
    return cast(list[Any], asyncio.run(app.list_tools()))


def write_reference(out_dir: Path) -> None:
    docs = tool_docs(_registry_tools())
    out_dir.mkdir(parents=True, exist_ok=True)
    by_ns: dict[str, list[ToolDoc]] = {}
    for d in docs:
        by_ns.setdefault(d.namespace, []).append(d)
    for ns, ns_docs in by_ns.items():
        (out_dir / f"{ns}.md").write_text(render_namespace(ns, ns_docs), encoding="utf-8")
    (out_dir / "index.md").write_text(render_index(docs), encoding="utf-8")


if __name__ == "__main__":
    write_reference(_REF_DIR)
    print(f"wrote reference to {_REF_DIR}", file=sys.stderr)
