#!/usr/bin/env bash
# Generate src/kdive/_buildinfo.py for baking into a built artifact (ADR-0041 decision 5).
# RELEASE is taken from $1 ("true"/"false") when given — release.yml passes "true", since
# the tag-triggered workflow is authoritative — otherwise derived from a live-git
# clean-exact-tag test. The commit + release are computed BEFORE the file is written so the
# (gitignored) file cannot affect the porcelain check.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="$repo_root/src/kdive/_buildinfo.py"

commit="$(git -C "$repo_root" rev-parse --short HEAD 2>/dev/null || echo unknown)"

release="${1:-}"
if [[ -z "$release" ]]; then
  version="$(cd "$repo_root" && uv version --short)"
  exact="$(git -C "$repo_root" describe --tags --exact-match HEAD 2>/dev/null || true)"
  if [[ "$exact" == "v$version" && -z "$(git -C "$repo_root" status --porcelain)" ]]; then
    release="true"
  else
    release="false"
  fi
fi

case "$release" in
true | false) ;;
*)
  echo "stamp-buildinfo.sh: unexpected release arg '$release' (expected 'true' or 'false')" >&2
  exit 1
  ;;
esac

if [[ "$release" == "true" ]]; then py_release="True"; else py_release="False"; fi

cat >"$target" <<EOF
# Generated by scripts/stamp-buildinfo.sh — do not edit, do not commit (gitignored).
COMMIT = "$commit"
RELEASE = $py_release
EOF
